export const ACTION_GET_WINNERS_STARTED = "GET_WINNERS_STARTED";
export const ACTION_GET_WINNERS_SUCCESS = "GET_WINNERS_SUCCESS";
export const ACTION_GET_WINNERS_FAILED = "GET_WINNERS_FAILED";


export const ACTION_CREATE_POST_STARTED = "CREATE_POST_STARTED";
export const ACTION_CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";